
# Example:
# gcr/shared/openai	gpt-4o_2024-05-13	gpt-4o	2024-05-13	36150	10	Modern Auth
model_list:
  - model_name: gpt-4o_2024-05-13
    litellm_params: &gpt-4o_2024-05-13
      model: azure/gpt-4o_2024-05-13
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: gpt-4o
    litellm_params:
      <<: *gpt-4o_2024-05-13
# gcr/shared/openai	gpt-4_0125-Preview	gpt-4	0125-Preview	10000	10	Modern Auth
  - model_name: gpt-4_0125-Preview
    litellm_params: &gpt-4_0125-Preview
      model: azure/gpt-4_turbo-2024-04-09
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: gpt-4
    litellm_params:
      <<: *gpt-4_0125-Preview
# gcr/shared/openai	gpt-4_turbo-2024-04-09	gpt-4	turbo-2024-04-09	151	10	Modern Auth
  - model_name: gpt-4_turbo-2024-04-09
    litellm_params: &gpt-4_turbo-2024-04-09
      model: azure/gpt-4_turbo-2024-04-09
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: gpt-4
    litellm_params:
      <<: *gpt-4_turbo-2024-04-09
# gcr/shared/openai	gpt-4-32k_0613	gpt-4-32k	0613	31	10	Modern Auth
  - model_name: gpt-4-32k_0613
    litellm_params: &gpt-4-32k_0613
      model: azure/gpt-4-32k_0613
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: gpt-4-32k
    litellm_params:
      <<: *gpt-4-32k_0613
# gcr/shared/openai	gpt-4_1106-Preview	gpt-4	1106-Preview	5510	10	Modern Auth
  - model_name: gpt-4_1106-Preview
    litellm_params: &gpt-4_1106-Preview
      model: azure/gpt-4_1106-Preview
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: gpt-4
    litellm_params:
      <<: *gpt-4_1106-Preview
# gcr/shared/openai	gpt-35-turbo_1106	gpt-35-turbo	1106	10120	10	Modern Auth
  - model_name: gpt-35-turbo_1106
    litellm_params: &gpt-35-turbo_1106
      model: azure/gpt-35-turbo_1106
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: gpt-35-turbo
    litellm_params:
      <<: *gpt-35-turbo_1106
# gcr/shared/openai	gpt-35-turbo-16k_0613	gpt-35-turbo-16k	0613	120	10	Modern Auth
  - model_name: gpt-35-turbo-16k_0613
    litellm_params: &gpt-35-turbo-16k_0613
      model: azure/gpt-35-turbo-16k_0613
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: gpt-35-turbo-16k
    litellm_params:
      <<: *gpt-35-turbo-16k_0613
# gcr/shared/openai	gpt-35-turbo-instruct_0914	gpt-35-turbo-instruct	0914	120	10	Modern Auth
  - model_name: gpt-35-turbo-instruct_0914
    litellm_params: &gpt-35-turbo-instruct_0914
      model: azure/gpt-35-turbo-instruct_0914
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: gpt-35-turbo-instruct
    litellm_params:
      <<: *gpt-35-turbo-instruct_0914
# gcr/shared/openai	babbage-002_1	babbage-002	1	120	10	Modern Auth
  - model_name: babbage-002_1
    litellm_params: &babbage-002_1
      model: azure/babbage-002_1
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: babbage-002
    litellm_params:
      <<: *babbage-002_1
# gcr/shared/openai	davinci-002_1	davinci-002	1	120	10	Modern Auth
  - model_name: davinci-002_1
    litellm_params: &davinci-002_1
      model: azure/davinci-002_1
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: davinci-002
    litellm_params:
      <<: *davinci-002_1
# gcr/shared/openai	text-embedding-ada-002_2	text-embedding-ada-002	2	120	10	Modern Auth
  - model_name: text-embedding-ada-002_2
    litellm_params: &text-embedding-ada-002_2
      model: azure/text-embedding-ada-002_2
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: text-embedding-ada-002
    litellm_params:
      <<: *text-embedding-ada-002_2
# gcr/shared/openai	gpt-4_vision-preview	gpt-4	vision-preview	15	60	Modern Auth
  - model_name: gpt-4_vision-preview
    litellm_params: &gpt-4_vision-preview
      model: azure/gpt-4_vision-preview
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: gpt-4
    litellm_params:
      <<: *gpt-4_vision-preview
# gcr/shared/openai	gpt-4o_2024-08-06	gpt-4o	2024-08-06	100	10	Modern Auth
  - model_name: gpt-4o_2024-08-06
    litellm_params: &gpt-4o_2024-08-06
      model: azure/gpt-4o_2024-08-06
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: gpt-4o
    litellm_params:
      <<: *gpt-4o_2024-08-06
# gcr/shared/openai	gpt-4o-mini_2024-07-18	gpt-4o-mini	2024-07-18	30000	60	Modern Auth
  - model_name: gpt-4o-mini_2024-07-18
    litellm_params: &gpt-4o-mini_2024-07-18
      model: azure/gpt-4o-mini_2024-07-18
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: gpt-4o-mini
    litellm_params:
      <<: *gpt-4o-mini_2024-07-18
# gcr/shared/openai	o1-mini_2024-09-12	o1-mini	2024-09-12	100	60	Modern Auth
  - model_name: o1-mini_2024-09-12
    litellm_params: &o1-mini_2024-09-12
      model: azure/o1-mini_2024-09-12
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: o1-mini
    litellm_params:
      <<: *o1-mini_2024-09-12
# gcr/shared/openai	o1-preview_2024-09-12	o1-preview	2024-09-12	167	60	Modern Auth
  - model_name: o1-preview_2024-09-12
    litellm_params: &o1-preview_2024-09-12
      model: azure/o1-preview_2024-09-12
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: o1-preview
    litellm_params:
      <<: *o1-preview_2024-09-12
# gcr/shared/openai	gpt-4_0314	gpt-4	0314	2	10	Modern Auth
  - model_name: gpt-4_0314
    litellm_params: &gpt-4_0314
      model: azure/gpt-4_0314
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-10-21"
  - model_name: gpt-4
    litellm_params:
      <<: *gpt-4_0314
# msra/shared/openai	gpt-4o_2024-05-13	gpt-4o	2024-05-13	36000	10	Modern Auth
  - model_name: gpt-4o_2024-05-13
    litellm_params: &gpt-4o_2024-05-13_msra
      model: azure/gpt-4o_2024-05-13
      api_base: https://trapi.research.microsoft.com/msra/shared
      api_version: "2024-10-21"
  - model_name: gpt-4o
    litellm_params:
      <<: *gpt-4o_2024-05-13_msra
# msra/shared/openai	gpt-4_0125-Preview	gpt-4	0125-Preview	10000	10	Modern Auth
  - model_name: gpt-4_0125-Preview
    litellm_params: &gpt-4_0125-Preview_msra
      model: azure/gpt-4_0125-Preview
      api_base: https://trapi.research.microsoft.com/msra/shared
      api_version: "2024-10-21"
  - model_name: gpt-4
    litellm_params:
      <<: *gpt-4_0125-Preview_msra
# msra/shared/openai	gpt-4_turbo-2024-04-09	gpt-4	turbo-2024-04-09	21	10	Modern Auth
  - model_name: gpt-4_turbo-2024-04-09
    litellm_params: &gpt-4_turbo-2024-04-09_msra
      model: azure/gpt-4_turbo-2024-04-09
      api_base: https://trapi.research.microsoft.com/msra/shared
      api_version: "2024-10-21"
  - model_name: gpt-4
    litellm_params:
      <<: *gpt-4_turbo-2024-04-09_msra
# msra/shared/openai	gpt-4-32k_0613	gpt-4-32k	0613	71	10	Modern Auth
  - model_name: gpt-4-32k_0613
    litellm_params: &gpt-4-32k_0613_msra
      model: azure/gpt-4-32k_0613
      api_base: https://trapi.research.microsoft.com/msra/shared
      api_version: "2024-10-21"
  - model_name: gpt-4-32k
    litellm_params:
      <<: *gpt-4-32k_0613_msra
# msra/shared/openai	gpt-4_1106-Preview	gpt-4	1106-Preview	5520	10	Modern Auth
  - model_name: gpt-4_1106-Preview
    litellm_params: &gpt-4_1106-Preview_msra
      model: azure/gpt-4_1106-Preview
      api_base: https://trapi.research.microsoft.com/msra/shared
      api_version: "2024-10-21"
  - model_name: gpt-4
    litellm_params:
      <<: *gpt-4_1106-Preview_msra
# msra/shared/openai	gpt-35-turbo_1106	gpt-35-turbo	1106	10240	10	Modern Auth
  - model_name: gpt-35-turbo_1106
    litellm_params: &gpt-35-turbo_1106_msra
      model: azure/gpt-35-turbo_1106
      api_base: https://trapi.research.microsoft.com/msra/shared
      api_version: "2024-10-21"
  - model_name: gpt-35-turbo
    litellm_params:
      <<: *gpt-35-turbo_1106_msra
# msra/shared/openai	gpt-4_vision-preview	gpt-4	vision-preview	30	60	Modern Auth
  - model_name: gpt-4_vision-preview
    litellm_params: &gpt-4_vision-preview_msra
      model: azure/gpt-4_vision-preview
      api_base: https://trapi.research.microsoft.com/msra/shared
      api_version: "2024-10-21"
  - model_name: gpt-4
    litellm_params:
      <<: *gpt-4_vision-preview_msra
# msra/shared/openai	gpt-4o_2024-08-06	gpt-4o	2024-08-06	2070	60	Modern Auth
  - model_name: gpt-4o_2024-08-06
    litellm_params: &gpt-4o_2024-08-06_msra
      model: azure/gpt-4o_2024-08-06
      api_base: https://trapi.research.microsoft.com/msra/shared
      api_version: "2024-10-21"
  - model_name: gpt-4o
    litellm_params:
      <<: *gpt-4o_2024-08-06_msra
# msra/shared/openai	gpt-4o-mini_2024-07-18	gpt-4o-mini	2024-07-18	40000	60	Modern Auth
  - model_name: gpt-4o-mini_2024-07-18
    litellm_params: &gpt-4o-mini_2024-07-18_msra
      model: azure/gpt-4o-mini_2024-07-18
      api_base: https://trapi.research.microsoft.com/msra/shared
      api_version: "2024-10-21"
  - model_name: gpt-4o-mini
    litellm_params:
      <<: *gpt-4o-mini_2024-07-18_msra
# msra/shared/openai	o1-preview_2024-09-12	o1-preview	2024-09-12	184	60	Modern Auth
  - model_name: o1-preview_2024-09-12
    litellm_params: &o1-preview_2024-09-12_msra
      model: azure/o1-preview_2024-09-12
      api_base: https://trapi.research.microsoft.com/msra/shared
      api_version: "2024-10-21"
  - model_name: o1-preview
    litellm_params:
      <<: *o1-preview_2024-09-12_msra
# msra/shared/openai	o1-mini_2024-09-12	o1-mini	2024-09-12	115	60	Modern Auth
  - model_name: o1-mini_2024-09-12
    litellm_params: &o1-mini_2024-09-12_msra
      model: azure/o1-mini_2024-09-12
      api_base: https://trapi.research.microsoft.com/msra/shared
      api_version: "2024-10-21"
  - model_name: o1-mini
    litellm_params:
      <<: *o1-mini_2024-09-12_msra
# msra/shared/openai	gpt-4o-realtime-preview_2024-10-01	gpt-4o-realtime-preview	2024-10-01	100	60	Modern Auth
  - model_name: gpt-4o-realtime-preview_2024-10-01
    litellm_params: &gpt-4o-realtime-preview_2024-10-01_msra
      model: azure/gpt-4o-realtime-preview_2024-10-01
      api_base: https://trapi.research.microsoft.com/msra/shared
      api_version: "2024-10-21"
  - model_name: gpt-4o-realtime-preview
    litellm_params:
      <<: *gpt-4o-realtime-preview_2024-10-01_msra
# msra/shared/openai	gpt-35-turbo_0301	gpt-35-turbo	0301	120	10	Modern Auth
  - model_name: gpt-35-turbo_0301
    litellm_params: &gpt-35-turbo_0301_msra
      model: azure/gpt-35-turbo_0301
      api_base: https://trapi.research.microsoft.com/msra/shared
      api_version: "2024-10-21"
  - model_name: gpt-35-turbo
    litellm_params:
      <<: *gpt-35-turbo_0301_msra
# To be formatted.
# gcr/shared/openai	o3-mini_2025-01-31	o3-mini	2025-01-31	200	60	Modern Auth
  - model_name: o3-mini_2025-01-31
    litellm_params: &o3-mini_2025-01-31_gcr
      model: azure/o3-mini_2025-01-31
      api_base: https://trapi.research.microsoft.com/gcr/shared
      api_version: "2024-12-01-preview"
  - model_name: o3-mini
    litellm_params:
      <<: *o3-mini_2025-01-31_gcr
# msra/shared/openai	o3-mini_2025-01-31	o3-mini	2025-01-31	100	60	Modern Auth
  - model_name: o3-mini_2025-01-31
    litellm_params: &o3-mini_2025-01-31_msra
      model: azure/o3-mini_2025-01-31
      api_base: https://trapi.research.microsoft.com/msra/shared
      api_version: "2024-12-01-preview"
  - model_name: o3-mini
    litellm_params:
      <<: *o3-mini_2025-01-31_msra

litellm_settings:
  # callbacks: xytoy.llm.lite.proxy_handler_instance  it will not looking for package
  callbacks: custom_callbacks.proxy_handler_instance  # but looking for a file related to the config
  enable_azure_ad_token_refresh: true

router_settings:
  client_ttl: 300
  num_retries: 4  # make sure all points have been tried
