unique_backend:
  uni_dyn_params: &uni_dyn_params
    model: os.environ/CHAT_MODEL
    api_base: os.environ/AZURE_API_BASE
    api_version: os.environ/AZURE_API_VERSION
    # api_key: os.environ/AZURE_API_KEY
    # azure_ad_token: os.environ/AZURE_OPENAI_AD_TOKEN
    # azure_ad_token: oidc/file/~/deploy/helper_scripts/bin/litellm_live_token

model_list:
  # - model_name: uni_dyn_params
  - model_name: gpt-4o
    litellm_params:
      <<: *uni_dyn_params

litellm_settings:
  # callbacks: xytoy.llm.lite.proxy_handler_instance  it will not looking for package
  callbacks: custom_callbacks.proxy_handler_instance  # but looking for a file related to the config
  enable_azure_ad_token_refresh: true
