unique_backend:
  uni_dyn_params: &uni_dyn_params
    model: os.environ/CHAT_MODEL
    api_base: os.environ/AZURE_API_BASE
    api_version: os.environ/AZURE_API_VERSION
    api_key: os.environ/AZURE_API_KEY
    azure_ad_token: os.environ/AZURE_OPENAI_AD_TOKEN
    # azure_ad_token: oidc/file/~/deploy/helper_scripts/bin/litellm_live_token
  # gcraoai9ncusspot
  uni_gcraoai9ncusspot_gpt-4_0125-Preview: &uni_gcraoai9ncusspot_gpt-4_0125-Preview
    model: azure/gpt-4_0125-Preview
    api_base: https://gcraoai9ncusspot.openai.azure.com/
    api_version: 2024-08-01-preview
  uni_gcraoai9ncusspot_gpt-4_turbo-2024-04-09: &uni_gcraoai9ncusspot_gpt-4_turbo-2024-04-09
    model: azure/gpt-4_turbo-2024-04-09
    api_base: https://gcraoai9ncusspot.openai.azure.com/
    api_version: 2024-08-01-preview
  uni_gcraoai9ncusspot_gpt-4-32k_0613: &uni_gcraoai9ncusspot_gpt-4-32k_0613
    model: azure/gpt-4-32k_0613
    api_base: https://gcraoai9ncusspot.openai.azure.com/
    api_version: 2024-08-01-preview
  # gcrgpt4aoai9spot
  uni_gcrgpt4aoai9spot_gpt-4o_2024-05-13: &uni_gcrgpt4aoai9spot_gpt-4o_2024-05-13
    model: azure/gpt-4o_2024-05-13
    api_base: https://gcrgpt4aoai9spot.openai.azure.com/
    api_version: 2024-08-01-preview
  uni_gcrgpt4aoai9spot_gpt-4_1106-Preview: &uni_gcrgpt4aoai9spot_gpt-4_1106-Preview
    model: azure/gpt-4_1106-Preview
    api_base: https://gcrgpt4aoai9spot.openai.azure.com/
    api_version: 2024-08-01-preview
  uni_gcrgpt4aoai9spot_gpt-35-turbo_1106: &uni_gcrgpt4aoai9spot_gpt-35-turbo_1106
    model: azure/gpt-35-turbo_1106
    api_base: https://gcrgpt4aoai9spot.openai.azure.com/
    api_version: 2024-08-01-preview
  # gcrgpt4aoai5c: gpt-35-turbo_0301 (120k), gpt-4o_2024-08-06(25k), gpt-4o-mini_2024-07-18(1000k)
  uni_gcrgpt4aoai5c_gpt-35-turbo_0301: &uni_gcrgpt4aoai5c_gpt-35-turbo_0301
    model: azure/gpt-35-turbo_0301
    api_base: https://gcrgpt4aoai5c.openai.azure.com/
    api_version: 2024-08-01-preview
  uni_gcrgpt4aoai5c_gpt-4o_2024-08-06: &uni_gcrgpt4aoai5c_gpt-4o_2024-08-06
    model: azure/gpt-4o_2024-08-06
    api_base: https://gcrgpt4aoai5c.openai.azure.com/
    api_version: 2024-08-01-preview
  uni_gcrgpt4aoai5c_gpt-4o-mini_2024-07-18: &uni_gcrgpt4aoai5c_gpt-4o-mini_2024-07-18
    model: azure/gpt-4o-mini_2024-07-18
    api_base: https://gcrgpt4aoai5c.openai.azure.com/
    api_version: 2024-08-01-preview
  # gcrgpt4aoai5:  gpt-4-32k_0613 (10k),  gpt-4o_2024-08-06 (25k) gpt-4o-mini_2024-07-18 (1000k)
  uni_gcrgpt4aoai5_gpt-4-32k_0613: &uni_gcrgpt4aoai5_gpt-4-32k_0613
    model: azure/gpt-4-32k_0613
    api_base: https://gcrgpt4aoai5.openai.azure.com/
    api_version: 2024-08-01-preview
  uni_gcrgpt4aoai5_gpt-4o_2024-08-06: &uni_gcrgpt4aoai5_gpt-4o_2024-08-06
    model: azure/gpt-4o_2024-08-06
    api_base: https://gcrgpt4aoai5.openai.azure.com/
    api_version: 2024-08-01-preview
  uni_gcrgpt4aoai5_gpt-4o-mini_2024-07-18: &uni_gcrgpt4aoai5_gpt-4o-mini_2024-07-18
    model: azure/gpt-4o-mini_2024-07-18
    api_base: https://gcrgpt4aoai5.openai.azure.com/
    api_version: 2024-08-01-preview
  # gcraoai9wus3spot
  uni_gcraoai9wus3spot_gpt-4_1106-Preview: &uni_gcraoai9wus3spot_gpt-4_1106-Preview
    model: azure/gpt-4_1106-Preview
    api_base: https://gcraoai9wus3spot.openai.azure.com/
    api_version: 2024-08-01-preview
  uni_gcraoai9wus3spot_gpt-4_0125-Preview: &uni_gcraoai9wus3spot_gpt-4_0125-Preview
    model: azure/gpt-4_0125-Preview
    api_base: https://gcraoai9wus3spot.openai.azure.com/
    api_version: 2024-08-01-preview
  uni_gcraoai9wus3spot_gpt-4o_2024-05-13: &uni_gcraoai9wus3spot_gpt-4o_2024-05-13
    model: azure/gpt-4o_2024-05-13
    api_base: https://gcraoai9wus3spot.openai.azure.com/
    api_version: 2024-08-01-preview

model_list:

  # More specific model (normally you should access this)
  # https://gcraoai9ncusspot.openai.azure.com/
  - model_name: gpt-4-0125
    litellm_params:
      <<: *uni_gcraoai9ncusspot_gpt-4_0125-Preview
  - model_name: gpt-4-turbo-2024-04-09
    litellm_params:
      <<: *uni_gcraoai9ncusspot_gpt-4_turbo-2024-04-09
  - model_name: gpt-4-32k-0613
    litellm_params:
      <<: *uni_gcraoai9ncusspot_gpt-4-32k_0613
  # https://gcrgpt4aoai9spot.openai.azure.com/
  - model_name: gpt-4o-2024-05-13
    litellm_params:
      <<: *uni_gcrgpt4aoai9spot_gpt-4o_2024-05-13
  - model_name: gpt-4-1106
    litellm_params:
      <<: *uni_gcrgpt4aoai9spot_gpt-4_1106-Preview
  - model_name: gpt-35-turbo-1106
    litellm_params:
      <<: *uni_gcrgpt4aoai9spot_gpt-35-turbo_1106
  # https://gcraoai9wus3spot.openai.azure.com/
  - model_name: gpt-4-1106
    litellm_params:
      <<: *uni_gcraoai9wus3spot_gpt-4_1106-Preview
  - model_name: gpt-4-0125
    litellm_params:
      <<: *uni_gcraoai9wus3spot_gpt-4_0125-Preview
  - model_name: gpt-4o-2024-05-13
    litellm_params:
      <<: *uni_gcraoai9wus3spot_gpt-4o_2024-05-13

  # gcrgpt4aoai5c
  - model_name: gpt-35-turbo-0301
    litellm_params:
      <<: *uni_gcrgpt4aoai5c_gpt-35-turbo_0301
  - model_name: gpt-4o-2024-08-06
    litellm_params:
      <<: *uni_gcrgpt4aoai5c_gpt-4o_2024-08-06
  - model_name: gpt-4o-mini-2024-07-18
    litellm_params:
      <<: *uni_gcrgpt4aoai5c_gpt-4o-mini_2024-07-18
  # gcrgpt4aoai5
  - model_name: gpt-4-32k-0613
    litellm_params:
      <<: *uni_gcrgpt4aoai5_gpt-4-32k_0613
  - model_name: gpt-4o-2024-08-06
    litellm_params:
      <<: *uni_gcrgpt4aoai5_gpt-4o_2024-08-06
  - model_name: gpt-4o-mini-2024-07-18
    litellm_params:
      <<: *uni_gcrgpt4aoai5_gpt-4o-mini_2024-07-18

  ## Ensemble of APIS;  If you don't care about the model version. Please Use this
  # Ensemble for gpt-4
  - model_name: gpt-4
    litellm_params:
      <<: *uni_gcrgpt4aoai9spot_gpt-4_1106-Preview
  - model_name: gpt-4
    litellm_params:
      <<: *uni_gcraoai9wus3spot_gpt-4_1106-Preview
  - model_name: gpt-4
    litellm_params:
      <<: *uni_gcraoai9wus3spot_gpt-4_0125-Preview
  - model_name: gpt-4
    litellm_params:
      <<: *uni_gcraoai9ncusspot_gpt-4_0125-Preview
  # Ensemble for gpt-4-turbo
  - model_name: gpt-4-turbo
    litellm_params:
      <<: *uni_gcraoai9ncusspot_gpt-4_turbo-2024-04-09
  # Ensemble for gpt-4-32k
  - model_name: gpt-4-32k
    litellm_params:
      <<: *uni_gcraoai9ncusspot_gpt-4-32k_0613
  - model_name: gpt-4-32k
    litellm_params:
      <<: *uni_gcrgpt4aoai5_gpt-4-32k_0613
  # Ensemble for gpt-4o-mini
  - model_name: gpt-4o-mini
    litellm_params:
      <<: *uni_gcrgpt4aoai5c_gpt-4o-mini_2024-07-18
  - model_name: gpt-4o-mini
    litellm_params:
      <<: *uni_gcrgpt4aoai5_gpt-4o-mini_2024-07-18
  # Ensemble for gpt-35-turbo
  - model_name: gpt-35-turbo
    litellm_params:
      <<: *uni_gcrgpt4aoai9spot_gpt-35-turbo_1106
  - model_name: gpt-35-turbo
    litellm_params:
      <<: *uni_gcrgpt4aoai5c_gpt-35-turbo_0301
  # Ensemble for gpt-4o
  - model_name: gpt-4o
    litellm_params:
      <<: *uni_gcrgpt4aoai9spot_gpt-4o_2024-05-13
  - model_name: gpt-4o
    litellm_params:
      <<: *uni_gcrgpt4aoai5c_gpt-4o_2024-08-06
  - model_name: gpt-4o
    litellm_params:
      <<: *uni_gcrgpt4aoai5_gpt-4o_2024-08-06
  - model_name: gpt-4o
    litellm_params:
      <<: *uni_gcraoai9wus3spot_gpt-4o_2024-05-13


  ## You should not access this in normal case!!!
  # for testing the unique backend
  - model_name: uni_gcraoai9ncusspot_gpt-4_0125-Preview
    litellm_params:
      <<: *uni_gcraoai9ncusspot_gpt-4_0125-Preview
  - model_name: uni_gcraoai9ncusspot_gpt-4_turbo-2024-04-09
    litellm_params:
      <<: *uni_gcraoai9ncusspot_gpt-4_turbo-2024-04-09
  - model_name: uni_gcraoai9ncusspot_gpt-4-32k_0613
    litellm_params:
      <<: *uni_gcraoai9ncusspot_gpt-4-32k_0613
  - model_name: uni_gcrgpt4aoai9spot_gpt-4o_2024-05-13
    litellm_params:
      <<: *uni_gcrgpt4aoai9spot_gpt-4o_2024-05-13
  - model_name: uni_gcrgpt4aoai9spot_gpt-4_1106-Preview
    litellm_params:
      <<: *uni_gcrgpt4aoai9spot_gpt-4_1106-Preview
  - model_name: uni_gcrgpt4aoai9spot_gpt-35-turbo_1106
    litellm_params:
      <<: *uni_gcrgpt4aoai9spot_gpt-35-turbo_1106
  # gcraoai9wus3spot unique point
  - model_name: uni_gcraoai9wus3spot_gpt-4_1106-Preview
    litellm_params:
      <<: *uni_gcraoai9wus3spot_gpt-4_1106-Preview
  - model_name: uni_gcraoai9wus3spot_gpt-4_0125-Preview
    litellm_params:
      <<: *uni_gcraoai9wus3spot_gpt-4_0125-Preview
  - model_name: uni_gcraoai9wus3spot_gpt-4o_2024-05-13
    litellm_params:
      <<: *uni_gcraoai9wus3spot_gpt-4o_2024-05-13
  # gcrgpt4aoai5c
  - model_name: uni_gcrgpt4aoai5c_gpt-35-turbo_0301
    litellm_params:
      <<: *uni_gcrgpt4aoai5c_gpt-35-turbo_0301
  - model_name: uni_gcrgpt4aoai5c_gpt-4o_2024-08-06
    litellm_params:
      <<: *uni_gcrgpt4aoai5c_gpt-4o_2024-08-06
  - model_name: uni_gcrgpt4aoai5c_gpt-4o-mini_2024-07-18
    litellm_params:
      <<: *uni_gcrgpt4aoai5c_gpt-4o-mini_2024-07-18
  # gcrgpt4aoai5 unique point
  - model_name: uni_gcrgpt4aoai5_gpt-4-32k_0613
    litellm_params:
      <<: *uni_gcrgpt4aoai5_gpt-4-32k_0613
  - model_name: uni_gcrgpt4aoai5_gpt-4o_2024-08-06
    litellm_params:
      <<: *uni_gcrgpt4aoai5_gpt-4o_2024-08-06
  - model_name: uni_gcrgpt4aoai5_gpt-4o-mini_2024-07-18
    litellm_params:
      <<: *uni_gcrgpt4aoai5_gpt-4o-mini_2024-07-18
  # dynamic
  # - model_name: gpt-4
  #   litellm_params:
  #     <<: *uni_dyn_params
  # - model_name: gpt-4o
  #   litellm_params:
  #     <<: *uni_dyn_params
  #
  - model_name: uni_dyn_params
    litellm_params:
      <<: *uni_dyn_params
  - model_name: os.environ/EXP_MODEL
    litellm_params:
      <<: *uni_dyn_params

# No luck
# litellm_settings:
#   success_callback: ["langfuse"]

litellm_settings:
  # callbacks: xytoy.llm.lite.proxy_handler_instance  it will not looking for package
  callbacks: custom_callbacks.proxy_handler_instance  # but looking for a file related to the config
  enable_azure_ad_token_refresh: true

router_settings:
  client_ttl: 120
  num_retries: 4  # make sure all points have been tried
