model_list:
  - model_name: gpt-4
    litellm_params:
      model: azure/gpt-4_0125-Preview
      api_base: os.environ/AZURE_API_BASE
      api_version: os.environ/AZURE_API_VERSION
      azure_ad_token: os.environ/AZURE_OPENAI_AD_TOKEN
