description: RD-Agent-MLE

target:
  service: sing
  # name: mckinley01
  name: msrresrchlab
  workspace_name: RD-Agent

environment:
  # registry: singularitybase.azurecr.io
  # image: base/job/pytorch/acpt-2.2.1-py3.10-cuda12.1:20240312T225111416
  registry: rdagentappregistry.azurecr.io
  image: rd-agent-mle:latest

code:
  # local directory of the code. this will be uploaded to the server.
  local_dir: $CONFIG_DIR/code/

storage:
  shared_datastore:
    storage_account_name: epeastus
    container_name: rdagent
    mount_dir: /data/Blob_EastUS

env_defaults:
  GPUS: 1
  RSLEX_DNS_RESOLUTION_CONCURRENCY: 1000

jobs:
  - name: test_v100_32g_GPUs${GPUS}
    identity: managed
    tags: [Project_Name:RD-Agent]
    submit_args: 
      env:
        _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/e033d461-1923-44a7-872b-78f1d35a86dd/resourceGroups/RDAgentAPP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/RDAgent_MI"
        RSLEX_DNS_RESOLUTION_CONCURRENCY: 1000
    sku: 32G${GPUS}-V100
    process_count_per_node: 1
    sla_tier: Premium
    priority: high
    command:
    - pwd
    - df -h
    - nvidia-smi
    - export RSLEX_DNS_RESOLUTION_CONCURRENCY=1000
    - sleep 4000
