[[snippets]]
  description = "grep cn"
  command = "rg '[\\p{Han}]'"
  output = ""

[[snippets]]
  description = "conda create"
  command = "conda create -y -n <env_name=XXX> python=<py_version=3.8>"
  output = ""

[[snippets]]
  description = "rsync high freq used"
  command = "rsync  -avzrP -e ssh XXX XXX  # z(compression) P(progress)"
  output = ""

[[snippets]]
  description = "black format"
  command = "python -m black .  -l 120"
  output = ""

[[snippets]]
  description = "terminalizer record"
  command = "terminalizer record XXX -d zsh"
  output = ""

[[snippets]]
  description = "process tree"
  command = "pstree -pas"
  output = ""

[[snippets]]
  description = "jupyter --ip 0.0.0.0"
  command = "jupyter notebook --no-browser --port 9000 --ip 0.0.0.0"
  output = ""

[[snippets]]
  description = "jupyter --ip `hostname`"
  command = "jupyter notebook --no-browser --port 9000 --ip `hostname` # You can not access 127.0.0.1 when binding hostname"
  output = ""

[[snippets]]
  description = "tmux list pane"
  command = "tmux list-panes -a -F \"#{pane_pid} #{session_name}:#{window_index}:#{pane_index}\""
  output = ""

[[snippets]]
  description = "py-spy record"
  command = "py-spy record -o profile.svg --"
  output = ""

[[snippets]]
  description = "git add me qlib"
  command = "git remote add me git@github.com:you-n-g/qlib.git"
  output = ""

[[snippets]]
  description = "py-spy top"
  command = "sudo env \"PATH=$PATH\"  py-spy top --pid"
  output = ""

[[snippets]]
  description = "snakeviz"
  command = "snakeviz -s -H `hostname` stats_out"
  output = ""

[[snippets]]
  description = "py-spy dump"
  command = "sudo env \"PATH=$PATH\"  py-spy dump --pid"
  output = ""

[[snippets]]
  description = "autossh proxy"
  command = "autossh -R 6489:127.0.0.1:6489 XXX # http proxy deployed locally, XXX configured in .ssh/config"
  output = ""

[[snippets]]
  description = "fzf preview for output lines"
  command = "fzf  --preview \"echo {} | bat -l  Python --style plain # --color=always\" --preview-window :wrap"
  output = ""

[[snippets]]
  description = "tmux edit pane name"
  command = "printf '\\033]2;%s\\033\\\\' '<pane-name>'"
  output = ""

[[snippets]]
  description = "tmux enable boarder (this will conflict with vim-slime)"
  command = "tmux set pane-border-status top"
  output = ""

[[snippets]]
  description = "for each dir git status"
  command = "for d in `ls` ; do  cd $d ; echo \"=================`pwd`\" ;  git status  ; cd .. ;  done"
  output = ""

[[snippets]]
  description = "clone my style project"
  command = "python ./clone.py all online_V05 online_V06  /home/xiaoyang/repos/online3rd_projects/V05 /home/xiaoyang/repos/online3rd_projects/V06"
  output = ""

[[snippets]]
  description = "conda clone"
  command = "conda create --name <env_name=online_V06>_gpu --clone <env_name=online_V06>"
  output = ""

[[snippets]]
  description = "reload tmux config"
  command = "tmux source ~/.tmux.conf"
  output = ""

[[snippets]]
  description = "start mlflow ui with long timeout"
  command = "GUNICORN_CMD_ARGS='--timeout 120'  mlflow ui -h `hostname` -p <port=5000>"
  output = ""

[[snippets]]
  description = "initial the tmux session for coding"
  command = "tmux rename-window code ; tmux new-window -n code_shell ; tmux new-window -n ops ; tmux new-window -n ops_shell ; tmux new-window -n service"
  output = ""

[[snippets]]
  description = "my repos"
  command = "git clone git@ssh.dev.azure.com:v3/you-n-g/qutils/cluster_manager ; git clone git@ssh.dev.azure.com:v3/you-n-g/qutils/qutils"
  output = ""

[[snippets]]
  description = "grep with ignore"
  command = "rg  --no-ignore --no-ignore-dot <grep_pattern=XXX> <grep_path=.>"
  output = ""

[[snippets]]
  description = "clean jupyter output"
  command = "ipynb_output_filter.py < <notebook=name.ipynb> > _yx_tmp  &&  mv _yx_tmp <notebook=name.ipynb> "
  output = "Nothing"

[[snippets]]
  description = "add git ignore"
  command = "cp ~/deploy/configs/git/py.gitignore .gitignore"
  output = ""

[[snippets]]
  description = "Forward proxy"
  command = "ssh xiaoyang@52.229.162.130 -L0.0.0.0:6489:0.0.0.0:6489  -D 0.0.0.0:8964"
  output = ""

[[snippets]]
  description = "agedu"
  command = "agedu --auth none -f agedu.dat -w --address 0.0.0.0:5432"
  output = ""

[[snippets]]
  description = "install favorate package"
  command = "sh ~/deploy/deploy_apps/install_fav_py_pack.sh"
  output = ""

[[snippets]]
  description = "python minimal install after create conda env"
  command = "pip install ipdb ipython neovim fire yapf pylint"
  output = ""

[[snippets]]
  description = "conda remove"
  command = "conda remove --name <env_name=XXX> --all"
  output = ""

[[snippets]]
  description = "view view file head"
  command = "head -n <top=50> <fname=600519.csv> | vim -"
  output = ""

[[snippets]]
  description = "git clean all untracked data"
  command = "git clean -d -x -f"
  output = ""

[[snippets]]
  description = "create qlib-based project"
  command = "mkdir <name> && cd <name> && cp.py --name <name> --py_ver 3.8 all --inst_qlib"
  output = ""

[[snippets]]
  description = "install my env"
  command = "sudo apt-get install -y git curl &&  git clone https://github.com/you-n-g/deploy && cd deploy &&  ./deploy.sh  # make sure you can sudo without password"
  output = ""

[[snippets]]
  description = "docker run, interactive, and remove example"
  command = "docker run -it --rm <img=kaggle/python:latest> /bin/bash"
  output = ""
